import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="header w-full fi p-4 fixed top-0 left-0 right-0 z-50">
          <div className="flex justify-between itesm-cecnter w-full px-8 py-2 border-b-white border-b-[thin] shadow-lg bg-transparent ">
            <div className="flex items-center ">
              <Image
                src="/assets/logo.svg"
                alt="Logo"
                width={40}
                height={40}
                priority
              />
              <h1 className="text-2xl font-bold ml-4">Mcommerece</h1>
            </div>
            <div className="flex justify-center gap-4">
              <ul className="flex items-center gap-4">
                <li>Men's</li>
                <li>Women</li>
                <li>Electronics</li>
              </ul>
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
