import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/components/header";
import { CartContextProvider } from "@/context/cartProvider";
import "./globals.css";
import { Footer } from "@/components/footer";
import { Cart } from "@/components/cart";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartContextProvider>
          <Header />
          <Cart />
          {children}
        </CartContextProvider>
        <Footer />
      </body>
    </html>
  );
}
